export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_SEARCH_USER ='SET_SEARCH_USER';
export const SET_CURRENT_NAME = 'SET_CURRENT_NAME';
export const SET_CURRENT_TOKEN = 'SET_CURRENT_TOKEN';
export const SET_SEARCH_FAILURE ='SET_SEARCH_FAILURE';